#### Build and tests all pushes, also code coverage
name: ðŸ› ï¸ CI build & test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 2 * * *" # run at 2 AM UTC
jobs:
  build:
    name: ðŸ”¨ Build and test (CI)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    strategy:
      matrix:
        dotnet-version: [6.0, 7.0, 8.0, 9.0]
    
    steps:
      - name: ðŸ“¤ Checkout the repository
        uses: actions/checkout@main

      - name: ðŸ¥… Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: ðŸ› ï¸ Build code
        run: dotnet build --configuration Release
        # run: dotnet build --configuration Release -p:TreatWarningsAsErrors=true temprarily disabled due to missing xml comments.

      - name: ðŸ‘€ Unit Test
        run: |
          echo "## â” Unit test results" >> $GITHUB_STEP_SUMMARY
          dotnet test --no-build --configuration Release tests/Occurify.Tests/Occurify.Tests.csproj -- RunConfiguration.CollectSourceInformation=true
          dotnet test --no-build --configuration Release tests/Occurify.TimeZones.Tests/Occurify.TimeZones.Tests.csproj -- RunConfiguration.CollectSourceInformation=true
          dotnet test --no-build --configuration Release tests/Occurify.Astro.Tests/Occurify.Astro.Tests.csproj -- RunConfiguration.CollectSourceInformation=true
          dotnet test --no-build --configuration Release tests/Occurify.Reactive.Tests/Occurify.Reactive.Tests.csproj -- RunConfiguration.CollectSourceInformation=true