name: üì¶ Publish to NuGet
on:
  release:
    types:
      - released
      - prereleased
jobs:
  deploy_nuget:
    name: üì¶ Publish NuGet Packages
    runs-on: ubuntu-latest
    environment: CI - release environment
    steps:
      - name: üóÇÔ∏è Checkout the repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: üîñ Get version from latest tag
        id: version
        run: |
          latest=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo Current version:    $latest
          echo "version=$latest" >> $GITHUB_OUTPUT

      - name: ‚¨áÔ∏è Install .NET 9
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "9.0.x" # SDK Version

      - name: üéÅ Pack
        run: |
          dotnet pack ./src/Occurify/ --configuration Release -p:PackageVersion=${{ steps.version.outputs.version }} -p:Version=${{ steps.version.outputs.version }}
          dotnet pack ./src/Occurify.Astro/ --configuration Release -p:PackageVersion=${{ steps.version.outputs.version }} -p:Version=${{ steps.version.outputs.version }}
          dotnet pack ./src/Occurify.Reactive/ --configuration Release -p:PackageVersion=${{ steps.version.outputs.version }} -p:Version=${{ steps.version.outputs.version }}
          dotnet pack ./src/Occurify.TimeZones/ --configuration Release -p:PackageVersion=${{ steps.version.outputs.version }} -p:Version=${{ steps.version.outputs.version }}
        
      - name: üì® Push to NuGet
        run: dotnet nuget push **/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
